#!/bin/bash

if [ ! -f '.vagrant/ssh-config' ]; then
  echo "Caching Vagrant SSH options in .vagrant/ssh-config"
  vagrant ssh-config > '.vagrant/ssh-config'
fi

ssh -F '.vagrant/ssh-config' -o LogLevel=quiet -c blowfish -t default -- "cd /vagrant && ./node_modules/gulp/bin/gulp.js ${*}"
